Feature/auth tests
wojdanowski/moodUpApi pull request #21
Opened 2021-01-25 09:59 UTC by wojdanowski

- Set up auth env
- Add authStrategy test

2021-01-25 11:49 UTC, arkus7 requested changes

2021-01-25 11:49 UTC, arkus7 commented on server.js
> +server = app.listen(port, () => {
Why this statement is split into separate lines?
Can't it be `const`?

2021-01-25 11:49 UTC, arkus7 commented on tests/test_config.js
> +	stubbedIsAuthenticated.callsFake(originalIsAuthenticated);
Isn't there any other option to restore mocked function implementation?
Jest has `restoreMock` or sth like this, maybe sinon has similar method?

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
> -
I'd rather leave this empty line here. It helps you divide your actions in tests visually into calling function and making the assertions on the result of that function.

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
>  		it('should get all recipes and return status code 200', async function () {
The test is named `should get all recipes and return status code 200`.

How about splitting this test into two tests:
1. should return status code 200
2. should return all recipes from the database

And in the 2nd test you e.g test if the appropriate method is called to receive data from DB or that the response contains an array with the recipes?

So far you only have assertion for the later statement in the test name (that the status code is 200).

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
> +				console.log(`FAKE IS AUTHENTICATED !!!!!!!!!!!!!!!!!!!!!!!`);
Is this console.log necessary? :P

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
>  		it('should return status code 400', async function () {
Please include why it should return 400 Bad Request status in the test name, in this case `when the recipe ID is invalid` or something in this fashion.
It will help you find what causes the issue when your failing tests tell you exactly in what situation the code does not work as expected 😉

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
>  		it('should return status code 404', async function () {
As below, include `when there is no recipe with provided ID`

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
>  		it('should get one recipe and return status code 200  ', async function () {
I think the more appropriate name will be `should get recipe with provided ID`, because `one recipe` can be a random one 😉

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
>  const RECIPE_ID_CORRECT = '5fd790724a7ab216c8920314';
Is there always a recipe with such ID in the DB? If not, how you make your test code know that this is correct ID and it should return a recipe?

2021-01-25 11:49 UTC, arkus7 commented on tests/recipe.spec.js
>  const RECIPE_ID_WRONG = '5fd790724a7ab216!c8920315';
Looks pretty good to me, even if it probably isn't. How about making it really easy to see that the id is incorrect, like using `testId` as the value?

2021-01-25 11:49 UTC, arkus7 commented on tests/authStrategy.spec.js
> +		it('Should return a false', async function () {
In what situation it should return false? Always? **When token is invalid?**

2021-01-26 10:27 UTC, arkus7 approved these changes

2021-01-26 10:27 UTC, arkus7 commented on package.json
> +    "test": "mocha tests/*.spec.js --exit --timeout 60000"
Why such a long timeout? Tests should be really quick to run, otherwise, it's a pain in the ass...

2021-01-26 10:27 UTC, arkus7 commented on tests/authStrategy.spec.js
> +let dummyUser;
I'd move it to the describe block, it's not used anywhere else.

2021-01-26 10:27 UTC, arkus7 commented on tests/mockDb.js
> +getDummyRecipe = async () => {
missing `const`?

2021-01-26 10:27 UTC, arkus7 commented on tests/recipe.spec.js
> +let dummyRecipe;
I'd move these 2 lines into describe block

2021-01-26 10:27 UTC, arkus7 commented on tests/recipe.spec.js
> +				response.body.results === 2,
I'd extract `2` into some variable/const like `const expectedRecipesCount = 2;`
Don't use magick numbers ;)

2021-01-26 10:29 UTC, arkus7 commented
@wojdanowski Why do we need this `dump.rbd` file at all?

2021-01-26 10:33 UTC, wojdanowski commented on package.json
> +    "test": "mocha tests/*.spec.js --exit --timeout 60000"
mongo-memory server docs 
`Start Mocha with --timeout 60000 cause first download of MongoDB binaries may take a time.`
:)

2021-01-26 12:18 UTC, arkus7 approved these changes

2021-01-26 12:31 UTC, merged