Feature/type script
wojdanowski/moodUpApi pull request #23
Opened 2021-02-03 07:07 UTC by wojdanowski

2021-02-03 09:42 UTC, MoodupDev requested changes

2021-02-03 09:42 UTC, MoodupDev commented on package.json
> +    "start:debug": "node --nolazy --inspect-brk=38009 ./src/server.ts",
I'm not sure this will work with typescript. Modify it like this:

`node --nolazy --inspect=38009 -r ts-node/register ./src/server`

One change here regarding inspect flag:
 --inspect-brk forces code to stop on breakpoint before starting
 --inspect doesn't do the above
 
 https://nodejs.org/en/docs/guides/debugging-getting-started/

2021-02-03 09:42 UTC, MoodupDev commented on package.json
> +    "start:prod": "SET NODE_ENV=production&& nodemon ./src/server.ts",
There shouldn't be a need for backend to set NODE_ENV in script. You dotenv for this. Use one start script. Also nodemon shouldn't be use for production

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/authController.ts
> +const signToken = (id: string) => {
missing return type (you're returning `jwt.sign` result) - `(id: string): <returnType> => {...}`

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/authController.ts
> +) => {
return type `: void` if I'm not mistaken

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/errorController.ts
> +const handleDuplicateFieldsDB = (err: any) => {
method return type `AppError`?

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/uploadController.ts
> +const uploadImage = catchAsync(async (req: any, res: any, next: any) => {
any!

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/uploadController.ts
>  		if (err) return next(new AppError('File Upload Error', 400));
always use `{}` even for single if statements - reduces possibility of issues in the code.

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/uploadController.ts
> +	singleUpload(req, res, function (err: any) {
you can change function to arrow function if you want

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/uploadController.ts
> +	singleUpload(req, res, function (err: any) {
add return type

2021-02-03 09:42 UTC, MoodupDev commented on src/controllers/uploadController.ts
>  		if (err) return next(new AppError('File Upload Error', 400));
Use http-status-codes library here

2021-02-03 09:42 UTC, MoodupDev commented on src/models/userModel.ts
> +userSchema.pre<IUser>('save', async function (this: IUser, next) {
Add type to next

2021-02-03 09:42 UTC, MoodupDev commented on src/redis.ts
> +const redisClient: RedisClient = redis.createClient(redis_port, redis_url);
I would stick to camelCase here for redis_url and redis_port -> redisUrl and redisPort.

2021-02-03 09:42 UTC, MoodupDev commented on src/utils/apiFeatures.ts
> +	query: DocumentQuery<Document[], Document>;
use private / public modifiers. By default public is used. Use it for fields and for methods

https://www.typescriptlang.org/docs/handbook/classes.html#public-private-and-protected-modifiers

2021-02-03 09:42 UTC, MoodupDev commented on src/utils/apiFeatures.ts
> +	search() {
`: APIFeatures`

2021-02-03 09:42 UTC, MoodupDev commented on src/utils/catchAsync.ts
> +	return (req: any, res: any, next: any) => {
Are you sure it should be `any` here?

2021-02-03 09:42 UTC, MoodupDev commented on src/utils/terminate.ts
> +	const exit = (code: any) => {
`code` seems like a number type. Not sure about server. Perhaps you can debug it and see it's type

2021-02-03 09:42 UTC, MoodupDev commented on src/utils/terminate.ts
> +	return (code: any, reason: any) => (err: any, promise: any) => {
types

2021-02-03 09:42 UTC, MoodupDev commented on tsconfig.json
> +      // "noImplicitAny": false
remove comment if not used

2021-02-03 09:42 UTC, MoodupDev commented on tsconfig.json
> +      // "noImplicitAny": false
you can also add options like:

`"rootDir": "src"`
`"moduleResolution": "node"`
`"removeComments": true`
`"typeRoots": ["node_modules/@types"]`
`"allowJs": true`

check what are they responsible for before adding them (or not)

2021-02-03 09:42 UTC, MoodupDev commented on src/validators/validation.ts
> +const validDataToRequest = (
hmm, I'm not used to this approach, but I guess you'd want to make this method accept various types. You have to experiment a bit. Perhaps something like this (not sure if this will work):

```
export interface ReqValidated<T> extends Request {
	validData: T;
}

const validDataToRequest = <T>(req: ReqValidated<T>, res: Response, next: NextFunction): void => {
...
  req.validData = <T>matchedData(req);
...
}
```

2021-02-03 10:06 UTC, arkus7 requested changes

2021-02-03 10:06 UTC, arkus7 commented on package.json
> +    "start:prod": "SET NODE_ENV=production&& nodemon ./src/server.ts",
Please add space between node env and `&&`
btw, you don't need `SET` before `NODE_ENV` on UNIX systems.

2021-02-03 10:06 UTC, arkus7 commented on src/controllers/authController.ts
> +		parseInt(process.env.REDIS_EXPIRES_IN!)
Missing radix? `parseInt(process.env.REDIS_EXPIRES_IN!, 10)`

2021-02-03 10:06 UTC, arkus7 commented on src/controllers/authController.ts
> +		status: 'success',
How about extracting it to some const? Then you won't make a typo somewhere 😉

2021-02-03 10:06 UTC, arkus7 commented on src/controllers/authController.ts
> +		const userDetails: IUserTemplate = {
Why is this a `Template`?

2021-02-03 10:06 UTC, arkus7 commented on src/controllers/errorController.ts
> +const sendErrorDev = (err: any, res: Response) => {
Please use as few `any` as possible

2021-02-03 10:06 UTC, arkus7 commented on src/models/userModel.ts
> +	passwordConfirm: string | undefined;
Is confirmed password stored in DB too? What for?

2021-02-03 10:06 UTC, arkus7 commented on src/passport/strategies.ts
> +					else return resolve(decoded);
Else is not needed when using return

2021-02-03 10:06 UTC, arkus7 commented on src/passport/strategies.ts
> +		const verifyToken = (token: string, secret: string): Promise<any> => {
You should know the type of returned data here

2021-02-03 10:06 UTC, arkus7 commented on src/passport/strategies.ts
> +type decodedToken = {
Please use `CamelCase` for type aliases

2021-02-03 10:06 UTC, arkus7 commented on src/redis.ts
> +const redis_url: string = process.env.REDIS_URL!;
Please use `camelCale` for variables

2021-02-03 10:06 UTC, arkus7 commented on src/redis.ts
> +redisClient.on('connect', () => {
Where the connection is being initialized?

2021-02-03 10:06 UTC, arkus7 commented on src/redis.ts
> +			resolve('OK');
How about returning `true` if the action succeeded and `false` (or throwing an error) when not?

2021-02-03 10:06 UTC, arkus7 commented on src/utils/catchAsync.ts
> +export default (fn: any) => {
Why `any`?  Please add types here, at least `Function`

2021-02-03 10:06 UTC, arkus7 commented on src/utils/catchAsync.ts
> +	return (req: any, res: any, next: any) => {
Please add express types here

2021-02-03 10:06 UTC, arkus7 commented on src/utils/catchAsync.ts
> +		fn(req, res, next).catch(next);
So it seems you know the params that `fn` should accept, and it seems that `fn` is a `RequestHandler`

```ts
interface RequestHandler {
    (req: Request, res: Response, next: NextFunction): any;
  }
```
You'd probably need to make sure that this function returns a promise, so you can add a similar interface like
```ts
interface AsyncRequestHandler<T = any> {
    (req: Request, res: Response, next: NextFunction): Promise<T>;
  }
```

Note: `<T = any>` let typescript infer the type when it's possible. When not, it will use `any` as the type of returned promise.

2021-02-03 10:06 UTC, arkus7 commented on src/utils/terminate.ts
> +function terminate(server: any, options = { coredump: false, timeout: 500 }) {
I bet there is a type for `server`

2021-02-03 10:06 UTC, arkus7 commented on src/utils/terminate.ts
> +	const exit = (code: any) => {
`code` is probably `number`, not `any`

2021-02-03 10:06 UTC, arkus7 commented on src/utils/terminate.ts
> +	return (code: any, reason: any) => (err: any, promise: any) => {
Please add types

2021-02-03 14:08 UTC, wojdanowski commented on src/controllers/authController.ts
> +		const userDetails: IUserTemplate = {
It's later used to User.create(.... 
It cannot be IUser because IUser inherits fields from mongoose.Document so "const userDetails: IUser" gives :
`Type '{ name: any; email: any; password: any; passwordConfirm: any; role: string; }' is missing the following properties from type 'IUser': $ignore, $isDefault, $isDeleted, $isEmpty, and 46 more.ts(2740)`

2021-02-03 14:15 UTC, wojdanowski commented on src/models/userModel.ts
> +	passwordConfirm: string | undefined;
It's not. It's there to validate match on signup. PasswordConfirm is removed (set to undefined) from document on pre save. Never gets to the DB

2021-02-04 15:16 UTC, arkus7 approved these changes

2021-02-04 15:16 UTC, arkus7 commented on src/controllers/authController.ts
> +	return jwt.sign({ id: id }, process.env.JWT_SECRET!, {
You could use shorthand here `{ id }` as the key and variable used as the value have the same name

2021-02-04 15:16 UTC, arkus7 commented on src/controllers/authController.ts
> +		const userDetails: IUserTemplate = {
I guess you could name it `UserDocument`/`UserModel` and `User` for the interface. But that's fine

2021-02-04 15:16 UTC, arkus7 commented on src/controllers/uploadController.ts
> +const uploadImage = catchAsync(async (req: any, res: any, next: any) => {
Why not use `(req: Request, res: Response, next: NextFunction)`?

2021-02-04 15:16 UTC, arkus7 commented on src/controllers/uploadController.ts
>  		if (err) return next(new AppError('File Upload Error', 400));
Please add curly braces here

2021-02-04 15:16 UTC, arkus7 commented on src/passport/strategies.ts
> +type decodedToken = {
It should be `type DecodedToken = { ... }`

2021-02-04 15:16 UTC, arkus7 commented on package.json
> +    "start:watch": "nodemon --config './nodemon.json'"
You could also use `tsc-watch` instead of `nodemon`

2021-02-04 15:16 UTC, arkus7 commented on src/passport/strategies.ts
> +		let currentUser;
missing type, could be `let currentUser: IUserTemplate;`

2021-02-04 15:16 UTC, arkus7 commented on src/redis.ts
> +redisClient.on('connect', () => {
??

2021-02-04 15:16 UTC, arkus7 commented on src/utils/catchAsync.ts
> +export interface RequestHandler {
This interface is available in express types, no need to redefine it

2021-02-05 07:42 UTC, wojdanowski commented on src/redis.ts
> +redisClient.on('connect', () => {
automatically on redis.createClient()

2021-02-05 07:47 UTC, merged