Feature/web sockets
wojdanowski/moodUpApi pull request #27
Opened 2021-02-12 14:20 UTC by wojdanowski

2021-02-16 15:42 UTC, MoodupDev requested changes

2021-02-16 15:42 UTC, MoodupDev commented on src/controllers/docsController.ts
> +import { CONTENT_SEC_POLICY } from './../utils/headers';
Please either use full names or correct abbreviations: `CONTENT_SECURITY_POLICY` or `CSP`. I prefer full names though.

2021-02-16 15:42 UTC, MoodupDev commented on src/controllers/socketsController.ts
> +    res.sendFile(path.join(__dirname, '../public/sockets_test_html.html'), { headers: CONTENT_SEC_POLICY });
Is this for testing purposes? There is no need to publish this page.

2021-02-16 15:42 UTC, MoodupDev commented on src/public/sockets_test_html.html
> +<!doctype html>
Normally this would be part of the frontend app, not inside the backend repo.

2021-02-16 15:42 UTC, MoodupDev commented on src/tests/recipe.spec.ts
> +describe.skip('Recipes', (): void => {
remove skip

2021-02-16 15:42 UTC, MoodupDev commented on src/utils/tools.ts
> +export const verifyToken = (token: string, secret: string): Promise<DecodedToken | undefined> => {
is `undefined` in `Promise<DecodedToken | undefined>` necessary? I would change it to `Promise<DecodedToken>`

2021-02-16 15:42 UTC, MoodupDev commented on src/app.ts
> +app.use('/api/v1/testSockets', socketRouter);
could be `notifications` , `websocket` or something similar

2021-02-16 15:42 UTC, MoodupDev commented on src/app.ts
> +import socketRouter from './routes/socketsRoutes';
`socketRoutes`

2021-02-16 15:42 UTC, MoodupDev commented on src/controllers/authController.ts
> +  let decoded;
If you are declaring a variable without assigning it yet (like when using `const`), please add a type. Because now it's implicitly an `any`.

2021-02-16 15:42 UTC, MoodupDev commented on src/controllers/authController.ts
> +  let user;
Same as above

2021-02-17 09:10 UTC, wojdanowski commented on src/controllers/socketsController.ts
> +    res.sendFile(path.join(__dirname, '../public/sockets_test_html.html'), { headers: CONTENT_SEC_POLICY });
I had no reason to do this i guess...

2021-02-17 12:33 UTC, wojdanowski commented on src/controllers/docsController.ts
> +import { CONTENT_SEC_POLICY } from './../utils/headers';
ok

2021-02-17 12:33 UTC, wojdanowski commented on src/public/sockets_test_html.html
> +<!doctype html>
ok

2021-02-17 12:33 UTC, wojdanowski commented on src/tests/recipe.spec.ts
> +describe.skip('Recipes', (): void => {
ok

2021-02-17 12:34 UTC, wojdanowski commented on src/utils/tools.ts
> +export const verifyToken = (token: string, secret: string): Promise<DecodedToken | undefined> => {
done

2021-02-17 12:36 UTC, wojdanowski commented on src/controllers/authController.ts
> +  let decoded;
ok

2021-02-17 12:36 UTC, wojdanowski commented on src/controllers/authController.ts
> +  let user;
ok

2021-02-17 12:46 UTC, wojdanowski commented on src/app.ts
> +app.use('/api/v1/testSockets', socketRouter);
ok

2021-02-17 12:46 UTC, wojdanowski commented on src/app.ts
> +import socketRouter from './routes/socketsRoutes';
ok

2021-02-17 13:08 UTC, MoodupDev commented on src/socket/socket.ts
> +          const user: IUser | null = await User.findById(decoded.id);
hmm, in this case I would either remove `| null` part, or if it's not possible, remove typing here - it's a const so from `User.findById` we know right away what type it will be

2021-02-17 13:08 UTC, MoodupDev commented on src/socket/socket.ts
> +  static getConnection(): Socket | null {
Remove `| null`, you don't have to explicitly type it.

2021-02-17 13:08 UTC, MoodupDev commented on src/utils/tools.ts
> +      if (err) return reject(new AppError(err.message, StatusCodes.UNAUTHORIZED));
Do not use 1 liner ifs! Always in curly brackets.

2021-02-17 13:08 UTC, MoodupDev commented on src/utils/tools.ts
> +      if (err) return reject(new AppError(err.message, StatusCodes.UNAUTHORIZED));
Here if you really want to have one line here then you can do something like this:
```
jwt.verify(token, secret, (err, decoded) => err ? reject(new AppError(err.message, StatusCodes.UNAUTHORIZED)) : 
resolve(decoded as DecodedToken)
```

You have to decide though if it's more readable or not (always prefer readability over reducing number of lines; sometimes it's better to even sacrifice performance - if it's only a little bit - over readability)

2021-02-17 13:08 UTC, MoodupDev commented on src/socket/socket.ts
> +  socket: socketIo.Socket | null;
Remove  `| null`, every type can be null or undefined

2021-02-17 13:08 UTC, MoodupDev commented on src/passport/strategies.ts
> +    if (!decoded || !decoded.id) {
Try changing `!decoded || !decoded.id` -> `!decoded?.id`. I think it should work.

2021-02-17 13:08 UTC, MoodupDev commented on package.json
> +    "test": "ts-mocha ./src/tests/*.spec.ts --exit --timeout 60000",
You can reorganize here a little bit - I would put `test` script either after or before `lint` and `format` scripts, but after all `start` tests

2021-02-17 13:09 UTC, MoodupDev approved these changes

2021-02-17 13:28 UTC, wojdanowski commented on src/utils/tools.ts
> +      if (err) return reject(new AppError(err.message, StatusCodes.UNAUTHORIZED));
ok

2021-02-17 13:28 UTC, wojdanowski commented on src/socket/socket.ts
> +          const user: IUser | null = await User.findById(decoded.id);
ok

2021-02-17 13:31 UTC, wojdanowski commented on src/socket/socket.ts
> +  static getConnection(): Socket | null {
no because strictNullChecks = true

2021-02-17 13:32 UTC, wojdanowski commented on src/socket/socket.ts
> +  socket: socketIo.Socket | null;
no because strictNullChecks = true

2021-02-17 13:35 UTC, wojdanowski commented on src/passport/strategies.ts
> +    if (!decoded || !decoded.id) {
ok

2021-02-17 13:37 UTC, wojdanowski commented on package.json
> +    "test": "ts-mocha ./src/tests/*.spec.ts --exit --timeout 60000",
ok

2021-02-17 13:39 UTC, merged